remote_theme: chrisrhymes/bulma-clean-theme
title: Shutter - Screenshot Tool
paginate: 5
paginate_path: "/blog/page:num"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Michael Kogan"
      layout: post
#      image: https://via.placeholder.com/1200x800
#      show_sidebar: true