theme: bulma-clean-theme
title: Shutter - Screenshot Tool
description: Shutter - Screenshot Tool website
paginate: 5
paginate_path: "/blog/page:num"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
      hero_image: /assets/img/shutter.svg
  -
    scope:
      path: ""
      type: "posts"
    values:
#      author: "Michael Kogan"
      layout: post
#      image: https://via.placeholder.com/1200x800
#      show_sidebar: true

plugins:
  - jekyll-feed
