[build]
  command = "jekyll build"
  publish = "_site/"

[[redirects]]
  from = "/feed/atom"
  to = "/feed.xml"

[[redirects]]
  from = "/feed"
  to = "/feed.xml"

[[redirects]]
  from = "/about"
  to = "/"
  force = true

[[redirects]]
  from = "/about/about-the-team"
  to = "/team"
[[redirects]]
  from = "/about-the-team"
  to = "/team"
[[redirects]]
  from = "/about/team"
  to = "/team"

[[redirects]]
  from = "/downloads"
  to = "/downloads/third-party-packages"
[[redirects]]
  from = "/faq-help/ppa-installation-guide/"
  to = "/downloads/third-party-packages"

[[redirects]]
  from = "/preview/screencasts"
  to = "/screenshots/screencasts"

[[redirects]]
  from = "/preview/*"
  to = "/screenshots"

[[redirects]]
  from = "/category/news"
  to = "/tag/news"
[[redirects]]
  from = "/category/release"
  to = "/tag/release"
[[redirects]]
  from = "/category/*"
  to = "/blog"

[[redirects]]
  from = "/2018/09/quick-bug-fix-in-0-94-2"
  to = "/releases/0.94.2"
  force = true
[[redirects]]
  from = "/2018/09/new-bug-fix-release-0-94-1"
  to = "/releases/0.94.1"
  force = true

[[redirects]]
  from = "/*"
  to = "https://shutter-project-wp-import.netlify.app/:splat"
  status = 200
